[package]
name = "CNTranslator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.5"
actix-files = "0.6.0-beta.8"
chinese_dictionary = "2.1.2"